# Generated by Django 5.1.15 on 2026-06-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_cancelled_at_order_delivered_at_order_paid_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_intent_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
