# Generated by Django 5.1.15 on 2026-06-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_specifications_and_reviews"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_price_9b1a5f_idx",
            old_name="products_pr_price_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_is_acti_ca4d9a_idx",
            old_name="products_pr_active_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_is_feat_a5d7cd_idx",
            old_name="products_pr_featured_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_stock_4d23d5_idx",
            old_name="products_pr_stock_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_pr_categor_6c8292_idx",
            old_name="products_pr_cat_act_crt_idx",
        ),
        migrations.RenameIndex(
            model_name="review",
            new_name="products_re_product_9ea0ee_idx",
            old_name="products_re_product_created_idx",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
