# Generated by Django 5.1.15 on 2026-06-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="couponredemption",
            options={"ordering": ["-created_at"]},
        ),
    ]
